apiVersion: v1
kind: Service
metadata:
  name: {{ include "beamforming.fullname" . }}-metrics
  labels:
    {{- include "beamforming.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "beamforming.selectorLabels" . | nindent 4 }}
